import { pgTable, serial, text, boolean, timestamp } from "drizzle-orm/pg-core";

export const applications = pgTable("applications", {
  id: serial().primaryKey(),
  ref: text().notNull().unique(),
  status: text().notNull().default("new"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  dob: text().notNull(),
  gender: text().notNull(),
  nationality: text().notNull(),
  category: text().notNull(),
  idNo: text("id_no").notNull().unique(),
  phone: text().notNull(),
  email: text().notNull().unique(),
  whatsapp: text(),
  district: text().notNull(),
  school: text().notNull(),
  year: text().notNull(),
  indexNo: text("index_no").notNull(),
  combo: text().notNull(),
  equivNo: text("equiv_no"),
  equivDate: text("equiv_date"),
  prog1: text(),
  col1: text(),
  prog2: text(),
  col2: text(),
  prog3: text(),
  col3: text(),
  payMethod: text("pay_method"),
  referral: text(),
  notes: text(),
  doc1: boolean().default(false),
  doc2: boolean().default(false),
  doc3: boolean().default(false),
  doc4: boolean().default(false),
  doc5: boolean().default(false),
  doc6: boolean().default(false),
  agree1: boolean().default(false),
  agree2: boolean().default(false),
  agree3: boolean().default(false),
  agree4: boolean().default(false),
  agree5: boolean().default(false),
  submittedAt: timestamp("submitted_at").defaultNow(),
});
