CREATE TABLE "applications" (
	"id" serial PRIMARY KEY,
	"ref" text NOT NULL UNIQUE,
	"status" text DEFAULT 'new' NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"dob" text NOT NULL,
	"gender" text NOT NULL,
	"nationality" text NOT NULL,
	"category" text NOT NULL,
	"id_no" text NOT NULL UNIQUE,
	"phone" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"whatsapp" text,
	"district" text NOT NULL,
	"school" text NOT NULL,
	"year" text NOT NULL,
	"index_no" text NOT NULL,
	"combo" text NOT NULL,
	"equiv_no" text,
	"equiv_date" text,
	"prog1" text,
	"col1" text,
	"prog2" text,
	"col2" text,
	"prog3" text,
	"col3" text,
	"pay_method" text,
	"referral" text,
	"notes" text,
	"doc1" boolean DEFAULT false,
	"doc2" boolean DEFAULT false,
	"doc3" boolean DEFAULT false,
	"doc4" boolean DEFAULT false,
	"doc5" boolean DEFAULT false,
	"doc6" boolean DEFAULT false,
	"agree1" boolean DEFAULT false,
	"agree2" boolean DEFAULT false,
	"agree3" boolean DEFAULT false,
	"agree4" boolean DEFAULT false,
	"agree5" boolean DEFAULT false,
	"submitted_at" timestamp DEFAULT now()
);
